name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4
      
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Dependencies kurulumu
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib pyinstaller
        
    - name: EXE dosyası oluştur (spec dosyası ile)
      run: |
        pyinstaller SnellLaw.spec
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SnellKanuluSimulatoru-exe
        path: dist/SnellKanuluSimulatoru.exe
