name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4
      
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Dependencies kurulumu (eski stabil versiyonlar)
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.24.3
        pip install matplotlib==3.7.1
        pip install pyinstaller==5.13.2
        
    - name: Test import
      run: |
        python -c "import numpy; print('NumPy version:', numpy.__version__)"
        python -c "import matplotlib; print('Matplotlib OK')"
        
    - name: EXE dosyası oluştur
      run: |
        pyinstaller --onefile --windowed ^
        --hidden-import=numpy ^
        --hidden-import=numpy.core ^
        --hidden-import=numpy.core._methods ^
        --hidden-import=numpy.lib.format ^
        --hidden-import=matplotlib ^
        --hidden-import=matplotlib.backends ^
        --hidden-import=matplotlib.backends.backend_tkagg ^
        --hidden-import=tkinter ^
        --collect-all=numpy ^
        --collect-all=matplotlib ^
        --name "SnellKanuluSimulatoru" ^
        SnellLaw.py
        
    - name: Test exe file
      run: |
        dir dist
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SnellKanuluSimulatoru-exe
        path: dist/SnellKanuluSimulatoru.exe
